/**
 * Cash flow forecast — deterministic projection layer.
 *
 * - `forecastRules`: recurring causes (SCI rent, salaries, installments…).
 * - `forecastEntries`: dated occurrences, generated by `expandRules`
 *   (idempotent via `derivedKey`) or created by hand.
 *
 * Safe regeneration: a derived entry edited by hand (`overridden: true`)
 * or already realized/cancelled is NEVER rewritten by `expandRules`.
 * The date-math lives in convex/lib/recurrence.ts (pure, tested by
 * tests/recurrence.test.ts).
 */

import { ConvexError, v } from 'convex/values'
import { internalMutation, mutation, query } from './_generated/server'
import { RESEND_FROM, resend } from './email'
import { cashAlertEmail } from './emailTemplates'
import { requireAppUser, requireOrgMember } from './lib/auth'
import { isAvailableAccount } from './lib/bankAccounts'
import { effectiveCategory, isValidForecastCategory } from './lib/categories'
import {
  MATCH_DATE_WINDOW_DAYS,
  suggestEntryMatches as pairEntryMatches,
} from './lib/entryMatching'
import { detectRecurringFlows } from './lib/recurrenceDetection'
import {
  addMonthsUtc,
  buildForecastGrid,
  buildMonthlyHistory,
  entryUpsertAction,
  expandOccurrences,
  monthKey,
  previousQuarter,
  ruleDerivedKey,
} from './lib/recurrence'
import { buildSearchText } from './lib/searchText'
import { computeVatPositionForOrg } from './transactions'
import type { GridTx, HistoryTx } from './lib/recurrence'
import type { DataModel, Doc, Id } from './_generated/dataModel'
import type { GenericMutationCtx, GenericQueryCtx } from 'convex/server'

// Local validators (deals.ts pattern) — keep aligned with schema.ts.
const directionValidator = v.union(v.literal('in'), v.literal('out'))

const frequencyValidator = v.union(
  v.literal('weekly'),
  v.literal('monthly'),
  v.literal('quarterly'),
  v.literal('yearly'),
)

const confidenceValidator = v.union(
  v.literal('confirmed'),
  v.literal('expected'),
  v.literal('probable'),
)

// Upper bound on the projection horizon (10 years), guardrail against an
// oversized expansion in a single mutation.
const MAX_HORIZON_MONTHS = 120

export function assertValidHorizon(horizonMonths: number) {
  if (
    !Number.isInteger(horizonMonths) ||
    horizonMonths < 1 ||
    horizonMonths > MAX_HORIZON_MONTHS
  ) {
    throw new ConvexError('invalid_horizon')
  }
}

/**
 * Resolves the org scope: `orgId` provided → that org (membership
 * required); absent → all orgs the user is a member of
 * (convex/aggregate.ts pattern).
 */
async function resolveOrgScope(
  ctx: GenericQueryCtx<DataModel> | GenericMutationCtx<DataModel>,
  orgId: Id<'organizations'> | undefined,
): Promise<Array<Id<'organizations'>>> {
  if (orgId) {
    await requireOrgMember(ctx, orgId)
    return [orgId]
  }
  const user = await requireAppUser(ctx)
  const memberships = await ctx.db
    .query('organizationMembers')
    .withIndex('by_user', (q) => q.eq('userId', user._id))
    .collect()
  return memberships.map((m) => m.orgId)
}

// ─── Rule field validation ──────────────────────────────────────────────────

function assertValidRuleFields(rule: {
  amountCents: number
  direction: 'in' | 'out'
  category?: string
  frequency: 'weekly' | 'monthly' | 'quarterly' | 'yearly'
  interval: number
  anchorDay: number
  startDate: number
  endDate?: number
}) {
  // Strictly positive integer cents — no monetary floats.
  if (!Number.isInteger(rule.amountCents) || rule.amountCents <= 0) {
    throw new ConvexError('invalid_amount')
  }
  // Category slug scoped to the direction (lib/categories.ts). Legacy
  // free-text categories on pre-existing rows stay untouched until edited.
  if (
    rule.category !== undefined &&
    !isValidForecastCategory(rule.direction, rule.category)
  ) {
    throw new ConvexError('invalid_category')
  }
  if (!Number.isInteger(rule.interval) || rule.interval < 1) {
    throw new ConvexError('invalid_interval')
  }
  const maxAnchor = rule.frequency === 'weekly' ? 7 : 31
  if (
    !Number.isInteger(rule.anchorDay) ||
    rule.anchorDay < 1 ||
    rule.anchorDay > maxAnchor
  ) {
    throw new ConvexError('invalid_anchor_day')
  }
  if (rule.endDate !== undefined && rule.endDate < rule.startDate) {
    throw new ConvexError('invalid_date_range')
  }
}

// ─── Rules ───────────────────────────────────────────────────────────────────

/**
 * Rule insertion (validation included) — core shared between the public
 * mutation and the agent tool (convex/agentToolsForecasts.ts).
 * The caller has already verified org membership.
 */
export async function insertRule(
  ctx: GenericMutationCtx<DataModel>,
  args: {
    orgId: Id<'organizations'>
    label: string
    amountCents: number
    direction: 'in' | 'out'
    category?: string
    frequency: 'weekly' | 'monthly' | 'quarterly' | 'yearly'
    interval?: number
    anchorDay: number
    startDate: number
    endDate?: number
    active?: boolean
  },
): Promise<Id<'forecastRules'>> {
  const interval = args.interval ?? 1
  assertValidRuleFields({ ...args, interval })
  return await ctx.db.insert('forecastRules', {
    orgId: args.orgId,
    label: args.label,
    amountCents: args.amountCents,
    direction: args.direction,
    category: args.category,
    frequency: args.frequency,
    interval,
    anchorDay: args.anchorDay,
    startDate: args.startDate,
    endDate: args.endDate,
    active: args.active ?? true,
    sourceType: 'manual',
  })
}

/** Creates a recurring rule (e.g. monthly SCI rent) in an org. */
export const createRule = mutation({
  args: {
    orgId: v.id('organizations'),
    label: v.string(),
    amountCents: v.number(),
    direction: directionValidator,
    category: v.optional(v.string()),
    frequency: frequencyValidator,
    interval: v.optional(v.number()), // default 1
    anchorDay: v.number(),
    startDate: v.number(),
    endDate: v.optional(v.number()),
    active: v.optional(v.boolean()), // default true
  },
  handler: async (ctx, args) => {
    await requireOrgMember(ctx, args.orgId)
    return await insertRule(ctx, args)
  },
})

/** An org's rules (forecast UI), sorted by label. */
export const listRules = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)
    const rules = await ctx.db
      .query('forecastRules')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()
    rules.sort((a, b) => a.label.localeCompare(b.label))
    return rules
  },
})

/**
 * Deletes a rule AND its still-untouched derived entries (pending, not
 * overridden). Realized / cancelled / hand-edited entries are kept —
 * that's history, not projection.
 */
export const deleteRule = mutation({
  args: { ruleId: v.id('forecastRules') },
  handler: async (ctx, { ruleId }) => {
    const rule = await ctx.db.get('forecastRules', ruleId)
    if (!rule) throw new ConvexError('not_found')
    await requireOrgMember(ctx, rule.orgId)

    const entries = await ctx.db
      .query('forecastEntries')
      .withIndex('by_rule', (q) => q.eq('ruleId', ruleId))
      .collect()
    let entriesRemoved = 0
    for (const entry of entries) {
      if (entry.status === 'pending' && !entry.overridden) {
        await ctx.db.delete('forecastEntries', entry._id)
        entriesRemoved += 1
      }
    }
    await ctx.db.delete('forecastRules', ruleId)
    return { entriesRemoved }
  },
})

/**
 * Updates a rule. Does not affect already-generated entries: re-run
 * `expandRules` to resync the unprotected occurrences.
 */
export const updateRule = mutation({
  args: {
    ruleId: v.id('forecastRules'),
    patch: v.object({
      label: v.optional(v.string()),
      amountCents: v.optional(v.number()),
      direction: v.optional(directionValidator),
      // `null` clears the category (absent = leave untouched — an optional
      // arg cannot carry `undefined` over the wire).
      category: v.optional(v.union(v.string(), v.null())),
      frequency: v.optional(frequencyValidator),
      interval: v.optional(v.number()),
      anchorDay: v.optional(v.number()),
      startDate: v.optional(v.number()),
      endDate: v.optional(v.number()),
      active: v.optional(v.boolean()),
    }),
  },
  handler: async (ctx, { ruleId, patch }) => {
    const rule = await ctx.db.get('forecastRules', ruleId)
    if (!rule) throw new ConvexError('not_found')
    await requireOrgMember(ctx, rule.orgId)
    // null (clear) validates as "no category"; a set category is checked
    // against the (possibly patched) direction.
    const { category: rawCategory, ...rest } = patch
    const category = rawCategory === null ? undefined : rawCategory
    assertValidRuleFields({ ...rule, ...rest, category })
    await ctx.db.patch('forecastRules', ruleId, {
      ...rest,
      // Patching `category: undefined` removes the field (clear).
      ...(rawCategory !== undefined ? { category } : {}),
    })
    return null
  },
})

// ─── Rule → occurrence expansion ─────────────────────────────────────────────

/**
 * Expands active rules into `forecastEntries` over `horizonMonths` months,
 * from max(startDate, now) to now + horizon. Idempotent: upsert by
 * `derivedKey` ("rule:{ruleId}:{YYYY-MM-DD}").
 *
 * - Missing entry → created (confidence `confirmed`, status `pending`).
 * - Existing unprotected entry → resync amount/label/category/direction.
 * - Protected entry (overridden, realized or cancelled) → SKIP.
 *
 * Without `orgId`: all orgs the user is a member of.
 */
export const expandRules = mutation({
  args: {
    orgId: v.optional(v.id('organizations')),
    horizonMonths: v.number(),
  },
  handler: async (ctx, { orgId, horizonMonths }) => {
    assertValidHorizon(horizonMonths)
    const orgIds = await resolveOrgScope(ctx, orgId)
    return await expandRulesForOrgs(ctx, orgIds, horizonMonths)
  },
})

/**
 * Expansion core (no auth) — shared between the public mutation and the
 * agent tool. The caller has already verified membership of the orgs.
 */
export async function expandRulesForOrgs(
  ctx: GenericMutationCtx<DataModel>,
  orgIds: Array<Id<'organizations'>>,
  horizonMonths: number,
) {
  const now = Date.now()
  const horizonEnd = addMonthsUtc(now, horizonMonths)

  let rulesProcessed = 0
  let created = 0
  let updated = 0
  let skippedProtected = 0

  for (const oid of orgIds) {
    const rules = await ctx.db
      .query('forecastRules')
      .withIndex('by_org', (q) => q.eq('orgId', oid))
      .collect()

    for (const rule of rules) {
      if (!rule.active) continue
      rulesProcessed += 1

      const occurrences = expandOccurrences(
        rule,
        Math.max(rule.startDate, now),
        horizonEnd,
      )

      for (const occurrence of occurrences) {
        const derivedKey = ruleDerivedKey(rule._id, occurrence)
        const existing = await ctx.db
          .query('forecastEntries')
          .withIndex('by_derivedKey', (q) => q.eq('derivedKey', derivedKey))
          .unique()

        // The create/update/skip decision is pure and tested in
        // tests/recurrence.test.ts — only the DB glue lives here.
        if (existing === null) {
          await ctx.db.insert('forecastEntries', {
            orgId: oid,
            date: occurrence,
            amountCents: rule.amountCents,
            direction: rule.direction,
            confidence: 'confirmed',
            status: 'pending',
            label: rule.label,
            category: rule.category,
            ruleId: rule._id,
            derivedKey,
            overridden: false,
            currency: 'EUR',
          })
          created += 1
        } else if (entryUpsertAction(existing) === 'skip') {
          skippedProtected += 1
        } else {
          // Resync from the rule (the date is frozen by the derivedKey).
          await ctx.db.patch('forecastEntries', existing._id, {
            amountCents: rule.amountCents,
            direction: rule.direction,
            label: rule.label,
            category: rule.category,
          })
          updated += 1
        }
      }
    }
  }

  return { rulesProcessed, created, updated, skippedProtected }
}

// ─── Real balance history ────────────────────────────────────────────────────

/**
 * Real end-of-month balance for the last `monthsBack` months (non-archived
 * EUR accounts only, same scope as the projected starting balance). The
 * backwards computation is pure (convex/lib/recurrence.ts:buildMonthlyHistory).
 */
async function computeCashHistoryForOrgs(
  ctx: GenericQueryCtx<DataModel>,
  orgIds: Array<Id<'organizations'>>,
  monthsBack: number,
  currentBalanceCents: number,
) {
  const now = Date.now()
  const nowDate = new Date(now)
  const windowStart = addMonthsUtc(
    Date.UTC(nowDate.getUTCFullYear(), nowDate.getUTCMonth(), 1),
    -monthsBack,
  )

  const transactions: Array<HistoryTx> = []
  for (const oid of orgIds) {
    const accounts = await ctx.db
      .query('bankAccounts')
      .withIndex('by_org', (q) => q.eq('orgId', oid))
      .collect()
    // Same availability scope as the starting balance (pledged accounts
    // are out of the "available cash" curve entirely). Closed accounts are
    // excluded too: their balance is 0-or-stale, and rebuilding backwards
    // from a balance they no longer contribute to would skew the curve.
    const eurAccountIds = new Set(
      accounts
        .filter((a) => isAvailableAccount(a) && a.currency === 'EUR')
        .map((a) => a._id),
    )
    const txs = await ctx.db
      .query('transactions')
      .withIndex('by_org_date', (q) =>
        q.eq('orgId', oid).gte('transactionDate', windowStart).lte(
          'transactionDate',
          now,
        ),
      )
      .collect()
    for (const tx of txs) {
      if (!eurAccountIds.has(tx.bankAccountId)) continue
      transactions.push({
        transactionDate: tx.transactionDate,
        amountCents: tx.amount,
        direction: tx.direction,
      })
    }
  }

  return buildMonthlyHistory({
    transactions,
    currentBalanceCents,
    monthsBack,
    now,
  })
}

// ─── Forecast → realized matching ────────────────────────────────────────────

const realizeModeValidator = v.union(
  v.literal('close'),
  v.literal('keepRemainder'),
)

/**
 * Realization core (no auth) — shared between the public mutation and the
 * agent tool. The caller has already verified membership of the entry's org.
 *
 * - `close` (default): the entry goes `realized` as-is; a gap between the
 *   forecast amount and the transaction amount is deliberate (still
 *   readable next to `realizedTransactionId`).
 * - `keepRemainder` (partial payment): the entry is split — the realized
 *   part takes the transaction amount, and the remainder stays expected as
 *   a NEW pure one-shot entry (no ruleId/derivedKey: it shows in the
 *   one-shot table and expandRules never touches it). Requires a pending
 *   entry and a transaction amount strictly below the forecast amount.
 */
export async function applyMarkEntryRealized(
  ctx: GenericMutationCtx<DataModel>,
  entry: Doc<'forecastEntries'>,
  transactionId: Id<'transactions'>,
  mode: 'close' | 'keepRemainder',
) {
  // Same guardrail in both modes: the transaction must belong to the same
  // org; we never touch the transaction itself (matchStatus, reconciled and
  // matchingDecisions stay exclusively managed by convex/transactions.ts).
  const tx = await ctx.db.get('transactions', transactionId)
  if (!tx || tx.orgId !== entry.orgId) {
    throw new ConvexError('transaction_wrong_org')
  }

  if (mode === 'keepRemainder') {
    if (entry.status !== 'pending') throw new ConvexError('not_pending')
    const remainderCents = entry.amountCents - tx.amount
    if (remainderCents <= 0) throw new ConvexError('no_remainder')
    await ctx.db.patch('forecastEntries', entry._id, {
      amountCents: tx.amount,
      status: 'realized',
      realizedTransactionId: transactionId,
    })
    await ctx.db.insert('forecastEntries', {
      orgId: entry.orgId,
      date: entry.date,
      amountCents: remainderCents,
      direction: entry.direction,
      confidence: entry.confidence,
      status: 'pending',
      label: entry.label,
      category: entry.category,
      overridden: false,
      currency: entry.currency,
    })
    return
  }

  await ctx.db.patch('forecastEntries', entry._id, {
    status: 'realized',
    realizedTransactionId: transactionId,
  })
}

/**
 * Marks an entry as realized by attaching it to a real transaction in the
 * same org (modeled on transactions.ts:matchTransaction). `mode` picks the
 * explicit decision when amounts differ: `close` (default — realize with
 * the gap) or `keepRemainder` (partial payment — the balance stays
 * expected). Cf. `applyMarkEntryRealized`.
 */
export const markEntryRealized = mutation({
  args: {
    entryId: v.id('forecastEntries'),
    transactionId: v.id('transactions'),
    mode: v.optional(realizeModeValidator),
  },
  handler: async (ctx, { entryId, transactionId, mode }) => {
    const entry = await ctx.db.get('forecastEntries', entryId)
    if (!entry) throw new ConvexError('not_found')
    await requireOrgMember(ctx, entry.orgId)
    await applyMarkEntryRealized(ctx, entry, transactionId, mode ?? 'close')
    return null
  },
})

// How far back a pending entry (overdue) is still offered for matching, and
// how many suggestions the UI card shows at most.
const SUGGEST_ENTRY_LOOKBACK_DAYS = 90
const SUGGEST_ENTRY_MAX = 20
const DAY_MS = 24 * 60 * 60 * 1000

/**
 * Suggested entry ↔ transaction reconciliations for the org: due or
 * overdue pending EUR entries (rule-derived occurrences INCLUDED — rents
 * are the main use case) paired with recent transactions on EUR accounts.
 * The pairing itself is pure and tested (lib/entryMatching.ts): direction +
 * date window + amount window, scored by amount/date/label, one transaction
 * suggested at most once. Transactions already attached to a realized entry
 * and `ignored` / `internal_transfer` rows are excluded.
 */
export const suggestForecastMatches = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)
    const now = Date.now()
    const entriesFrom = now - SUGGEST_ENTRY_LOOKBACK_DAYS * DAY_MS
    const entriesTo = now + MATCH_DATE_WINDOW_DAYS * DAY_MS

    // One org-wide read: the matchable window AND the set of transactions
    // already consumed by a realized entry (whatever their date).
    const allEntries = await ctx.db
      .query('forecastEntries')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()
    const usedTxIds = new Set(
      allEntries
        .map((e) => e.realizedTransactionId)
        .filter((id): id is Id<'transactions'> => id != null),
    )
    const matchable = allEntries.filter(
      (e) =>
        e.status === 'pending' &&
        e.currency === 'EUR' &&
        e.date >= entriesFrom &&
        e.date <= entriesTo,
    )
    if (matchable.length === 0) return []

    const accounts = await ctx.db
      .query('bankAccounts')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()
    const eurAccountIds = new Set(
      accounts.filter((a) => a.currency === 'EUR').map((a) => a._id),
    )

    const txs = await ctx.db
      .query('transactions')
      .withIndex('by_org_date', (q) =>
        q
          .eq('orgId', orgId)
          .gte('transactionDate', entriesFrom - MATCH_DATE_WINDOW_DAYS * DAY_MS)
          .lte('transactionDate', now),
      )
      .collect()
    const candidates = txs.filter(
      (tx) =>
        eurAccountIds.has(tx.bankAccountId) &&
        !usedTxIds.has(tx._id) &&
        tx.matchStatus !== 'ignored' &&
        tx.matchStatus !== 'internal_transfer',
    )

    const pairs = pairEntryMatches({
      entries: matchable.map((e) => ({
        id: e._id,
        date: e.date,
        amountCents: e.amountCents,
        direction: e.direction,
        label: e.label,
      })),
      transactions: candidates.map((tx) => ({
        id: tx._id,
        transactionDate: tx.transactionDate,
        amountCents: tx.amount,
        direction: tx.direction,
        searchText:
          tx.searchText ?? buildSearchText(tx.rawLabel, tx.counterparty),
      })),
    })

    const entryById = new Map(matchable.map((e) => [e._id as string, e]))
    const txById = new Map(candidates.map((tx) => [tx._id as string, tx]))
    return pairs.slice(0, SUGGEST_ENTRY_MAX).flatMap((pair) => {
      const entry = entryById.get(pair.entryId)
      const tx = txById.get(pair.transactionId)
      if (!entry || !tx) return []
      return [
        {
          entry: {
            _id: entry._id,
            date: entry.date,
            label: entry.label,
            amountCents: entry.amountCents,
            direction: entry.direction,
            confidence: entry.confidence,
            derivedFromRule: entry.ruleId != null,
          },
          transaction: {
            _id: tx._id,
            transactionDate: tx.transactionDate,
            rawLabel: tx.rawLabel,
            counterparty: tx.counterparty ?? null,
            amountCents: tx.amount,
          },
        },
      ]
    })
  },
})

// ─── Rule suggestions (recurrence detection) ─────────────────────────────────

// History window scanned for recurring flows.
const DETECTION_LOOKBACK_MONTHS = 12

/**
 * Recurring flows detected in the last 12 months of transactions that are
 * not covered by an active rule nor dismissed — candidates for forecast
 * rules, biggest amounts first. Detection is pure and tested
 * (lib/recurrenceDetection.ts); it only SUGGESTS — creating the rule stays
 * a human gesture through the prefilled rule dialog (createRule).
 */
export const suggestRules = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)
    const now = Date.now()
    const windowStart = addMonthsUtc(now, -DETECTION_LOOKBACK_MONTHS)

    // EUR accounts only — rule amounts are EUR cents.
    const accounts = await ctx.db
      .query('bankAccounts')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()
    const eurAccountIds = new Set(
      accounts.filter((a) => a.currency === 'EUR').map((a) => a._id),
    )

    const txs = await ctx.db
      .query('transactions')
      .withIndex('by_org_date', (q) =>
        q
          .eq('orgId', orgId)
          .gte('transactionDate', windowStart)
          .lte('transactionDate', now),
      )
      .collect()

    const rules = await ctx.db
      .query('forecastRules')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()
    const dismissed = await ctx.db
      .query('dismissedRuleSuggestions')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()

    return detectRecurringFlows({
      transactions: txs
        .filter((tx) => eurAccountIds.has(tx.bankAccountId))
        .map((tx) => ({
          transactionDate: tx.transactionDate,
          amountCents: tx.amount,
          direction: tx.direction,
          rawLabel: tx.rawLabel,
          counterparty: tx.counterparty ?? null,
          category: effectiveCategory(tx),
        })),
      existingRules: rules.map((rule) => ({
        direction: rule.direction,
        frequency: rule.frequency,
        amountCents: rule.amountCents,
        active: rule.active,
      })),
      dismissed: dismissed.map((d) => ({
        pattern: d.pattern,
        direction: d.direction,
      })),
    })
  },
})

/**
 * "Ignorer" on a suggested rule: remembers the (pattern, direction) so the
 * suggestion never comes back. No edit/delete surface in V1 (Convex
 * dashboard, like categoryRules).
 */
export const dismissRuleSuggestion = mutation({
  args: {
    orgId: v.id('organizations'),
    pattern: v.string(),
    direction: directionValidator,
  },
  handler: async (ctx, { orgId, pattern, direction }) => {
    const { user } = await requireOrgMember(ctx, orgId)
    await ctx.db.insert('dismissedRuleSuggestions', {
      orgId,
      pattern,
      direction,
      createdBy: user._id,
    })
    return null
  },
})

// ─── Upcoming entries (cockpit) ──────────────────────────────────────────────

// KPI/list windows of the cockpit "upcoming entries" section.
const UPCOMING_WINDOW_DAYS = 90
const UPCOMING_KPI_WINDOW_DAYS = 30

/**
 * Pending entries due within the next 90 days for the cockpit list —
 * OVERDUE ones included (same rollover stance as the grid: still expected,
 * just late), rule-derived occurrences included, EUR only, date ascending.
 * Ships the 30/90-day nets (in − out, overdue included) alongside so the
 * KPI band shares this single subscription.
 */
export const getUpcomingEntries = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)
    const now = Date.now()
    const horizonEnd = now + UPCOMING_WINDOW_DAYS * DAY_MS
    const kpiEnd = now + UPCOMING_KPI_WINDOW_DAYS * DAY_MS

    // No lower date bound: overdue entries surface until realized or
    // cancelled (dropping them would silently improve the outlook).
    const rows = await ctx.db
      .query('forecastEntries')
      .withIndex('by_org_and_date', (q) =>
        q.eq('orgId', orgId).lte('date', horizonEnd),
      )
      .collect()

    let net30Cents = 0
    let net90Cents = 0
    const entries = []
    for (const entry of rows) {
      if (entry.status !== 'pending' || entry.currency !== 'EUR') continue
      const signed =
        entry.direction === 'in' ? entry.amountCents : -entry.amountCents
      net90Cents += signed
      if (entry.date <= kpiEnd) net30Cents += signed
      entries.push({
        _id: entry._id,
        date: entry.date,
        label: entry.label,
        amountCents: entry.amountCents,
        direction: entry.direction,
        confidence: entry.confidence,
        derivedFromRule: entry.ruleId != null,
        overdue: entry.date < now,
      })
    }
    return { entries, net30Cents, net90Cents }
  },
})

// ─── Manual entry CRUD ───────────────────────────────────────────────────────

/**
 * An org's pure one-shot entries (`ruleId == null`) for the forecast UI,
 * date ascending (the `by_org_and_date` index order). Rule-derived
 * occurrences are intentionally excluded — they live on the rules surface
 * and in the projected-balance curve, not in this hand-managed list.
 */
export const listEntries = query({
  args: {
    orgId: v.id('organizations'),
    status: v.optional(
      v.union(
        v.literal('pending'),
        v.literal('realized'),
        v.literal('cancelled'),
      ),
    ),
  },
  handler: async (ctx, { orgId, status }) => {
    await requireOrgMember(ctx, orgId)
    const rows = await ctx.db
      .query('forecastEntries')
      .withIndex('by_org_and_date', (q) => q.eq('orgId', orgId))
      .collect()
    // A1: only pure one-shot entries; rule-derived occurrences are filtered.
    return rows.filter(
      (e) => e.ruleId == null && (status === undefined || e.status === status),
    )
  },
})

/** Creates a 100% manual entry (no rule, no derivedKey). */
export const createManualEntry = mutation({
  args: {
    orgId: v.id('organizations'),
    date: v.number(),
    amountCents: v.number(),
    direction: directionValidator,
    confidence: confidenceValidator,
    label: v.string(),
    category: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    await requireOrgMember(ctx, args.orgId)
    if (!Number.isInteger(args.amountCents) || args.amountCents <= 0) {
      throw new ConvexError('invalid_amount')
    }
    if (
      args.category !== undefined &&
      !isValidForecastCategory(args.direction, args.category)
    ) {
      throw new ConvexError('invalid_category')
    }
    return await ctx.db.insert('forecastEntries', {
      orgId: args.orgId,
      date: args.date,
      amountCents: args.amountCents,
      direction: args.direction,
      confidence: args.confidence,
      status: 'pending',
      label: args.label,
      category: args.category,
      overridden: false,
      currency: 'EUR',
    })
  },
})

/**
 * Edits an entry. If it is derived from a rule (`ruleId` non null), it
 * becomes `overridden: true`: expandRules will never rewrite it again.
 */
export const updateEntry = mutation({
  args: {
    entryId: v.id('forecastEntries'),
    patch: v.object({
      date: v.optional(v.number()),
      amountCents: v.optional(v.number()),
      direction: v.optional(directionValidator),
      confidence: v.optional(confidenceValidator),
      label: v.optional(v.string()),
      // `null` clears the category (absent = leave untouched).
      category: v.optional(v.union(v.string(), v.null())),
    }),
  },
  handler: async (ctx, { entryId, patch }) => {
    const entry = await ctx.db.get('forecastEntries', entryId)
    if (!entry) throw new ConvexError('not_found')
    await requireOrgMember(ctx, entry.orgId)
    if (
      patch.amountCents !== undefined &&
      (!Number.isInteger(patch.amountCents) || patch.amountCents <= 0)
    ) {
      throw new ConvexError('invalid_amount')
    }
    // Only a category being SET is validated — a legacy free-text category
    // on the row must not block an unrelated edit.
    const { category: rawCategory, ...rest } = patch
    if (
      typeof rawCategory === 'string' &&
      !isValidForecastCategory(patch.direction ?? entry.direction, rawCategory)
    ) {
      throw new ConvexError('invalid_category')
    }
    await ctx.db.patch('forecastEntries', entry._id, {
      ...rest,
      // Patching `category: undefined` removes the field (clear).
      ...(rawCategory !== undefined ? { category: rawCategory ?? undefined } : {}),
      // A hand-edited derived entry becomes protected from regeneration.
      ...(entry.ruleId ? { overridden: true } : {}),
    })
    return null
  },
})

/** Cancels an entry: it no longer counts toward the projected balance. */
export const cancelEntry = mutation({
  args: { entryId: v.id('forecastEntries') },
  handler: async (ctx, { entryId }) => {
    const entry = await ctx.db.get('forecastEntries', entryId)
    if (!entry) throw new ConvexError('not_found')
    await requireOrgMember(ctx, entry.orgId)
    await ctx.db.patch('forecastEntries', entry._id, { status: 'cancelled' })
    return null
  },
})

// ─── Forecast grid (category × month) ────────────────────────────────────────

/**
 * Category × month forecast grid + consumption-aware projected balance
 * (pure core: lib/recurrence.ts:buildForecastGrid — realized flows consume
 * the current month's pending flows per cell, overdue entries roll into the
 * current month; two scenarios: committed-only / with planned).
 *
 * Scope: single org, EUR, AVAILABLE accounts only (active, non-pledged —
 * same scope as the starting balance so the trajectory stays coherent).
 * Realized buckets derive from the pointage (lib/categories.ts
 * effectiveCategory); ignored/internal transfers are excluded.
 *
 * `history` (real end-of-month balances) ships alongside so the chart keeps
 * a single subscription.
 */
export const getForecastGrid = query({
  args: {
    orgId: v.id('organizations'),
    historyMonths: v.number(),
    horizonMonths: v.number(),
  },
  handler: async (ctx, { orgId, historyMonths, horizonMonths }) => {
    assertValidHorizon(historyMonths)
    assertValidHorizon(horizonMonths)
    await requireOrgMember(ctx, orgId)

    const grid = await computeForecastGridForOrg(
      ctx,
      orgId,
      historyMonths,
      horizonMonths,
    )
    const history = await computeCashHistoryForOrgs(
      ctx,
      [orgId],
      historyMonths,
      grid.startingBalanceCents,
    )
    return { ...grid, history }
  },
})

/**
 * Grid core (no auth) — shared between the public query above and the
 * agent / MCP `getForecastBalance` tool, which runs it with
 * `historyMonths: 0` (the current month's realized flows are still read,
 * so the consumption semantics hold). The caller has already verified
 * membership of the org.
 */
export async function computeForecastGridForOrg(
  ctx: GenericQueryCtx<DataModel>,
  orgId: Id<'organizations'>,
  historyMonths: number,
  horizonMonths: number,
) {
  const now = Date.now()

  // Available EUR accounts: starting balance + realized-flow scope.
  // Non-EUR available accounts are counted apart for visibility.
  const accounts = await ctx.db
    .query('bankAccounts')
    .withIndex('by_org', (q) => q.eq('orgId', orgId))
    .collect()
  const available = accounts.filter((a) => isAvailableAccount(a))
  const eurAvailable = available.filter((a) => a.currency === 'EUR')
  const ignoredNonEurAccounts = available.length - eurAvailable.length
  const eurAccountIds = new Set(eurAvailable.map((a) => a._id))
  const startingBalanceCents = eurAvailable.reduce(
    (sum, a) => sum + (a.currentBalance ?? 0),
    0,
  )

  // Realized flows over the history window (current month included).
  const nowDate = new Date(now)
  const currentMonthStart = Date.UTC(
    nowDate.getUTCFullYear(),
    nowDate.getUTCMonth(),
    1,
  )
  const windowStart = addMonthsUtc(currentMonthStart, -historyMonths)
  const txs = await ctx.db
    .query('transactions')
    .withIndex('by_org_date', (q) =>
      q.eq('orgId', orgId).gte('transactionDate', windowStart),
    )
    .collect()
  const realized: Array<GridTx> = []
  for (const tx of txs) {
    if (!eurAccountIds.has(tx.bankAccountId)) continue
    realized.push({
      transactionDate: tx.transactionDate,
      amountCents: tx.amount,
      direction: tx.direction,
      category: effectiveCategory(tx),
    })
  }

  // Pending entries — read WITHOUT a lower date bound so overdue ones
  // (date < current month) roll into the current month.
  const horizonEnd = addMonthsUtc(now, horizonMonths)
  const entries = await ctx.db
    .query('forecastEntries')
    .withIndex('by_org_and_date', (q) =>
      q.eq('orgId', orgId).lte('date', horizonEnd),
    )
    .collect()

  const grid = buildForecastGrid({
    realized,
    entries,
    startingBalanceCents,
    now,
    historyMonths,
    horizonMonths,
  })

  return { ...grid, startingBalanceCents, ignoredNonEurAccounts }
}

/**
 * Committed capital still to deploy on the org's signed deals:
 * `committedAmount` − realized "Versé" (sum of the deal-matched `out`
 * transactions — same derivation as the deal pages, never `paidAmount`).
 * This is the UNDATED committed layer of the forecast: real obligations
 * with no schedule — shown next to the curve, never invented into months.
 */
export const getCommittedPipeline = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)

    const deals = await ctx.db
      .query('deals')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()

    const rows: Array<{
      dealId: string
      name: string
      committedCents: number
      paidCents: number
      remainingCents: number
    }> = []
    for (const deal of deals) {
      if (deal.status !== 'active') continue
      const committed = deal.committedAmount ?? 0
      if (committed <= 0) continue
      const dealTxs = await ctx.db
        .query('transactions')
        .withIndex('by_deal', (q) => q.eq('dealId', deal._id))
        .collect()
      let paid = 0
      for (const tx of dealTxs) {
        if (tx.direction === 'out') paid += tx.amount
      }
      const remaining = committed - paid
      if (remaining <= 0) continue
      const target = await ctx.db.get('companies', deal.targetCompanyId)
      rows.push({
        dealId: deal._id,
        name: deal.name ?? target?.name ?? '—',
        committedCents: committed,
        paidCents: paid,
        remainingCents: remaining,
      })
    }
    rows.sort((a, b) => b.remainingCents - a.remainingCents)
    return {
      rows,
      totalRemainingCents: rows.reduce((sum, r) => sum + r.remainingCents, 0),
    }
  },
})

// ─── Monthly snapshots, threshold alerts, VAT suggestion (phase 4b) ──────────

// Snapshot horizon and alert evaluation window / cooldown.
const SNAPSHOT_HORIZON_MONTHS = 12
const ALERT_HORIZON_MONTHS = 3
const ALERT_COOLDOWN_MS = 7 * DAY_MS

/**
 * Monthly photo of every org's projection (cron, 1st of month 05:00 UTC —
 * convex/crons.ts). Runs WITHOUT auth on purpose (same exception family as
 * the backfills — cf. KNOWN_ISSUES « Cash flow forecast »). Idempotent per
 * (orgId, month): re-running the same month skips already-captured orgs, so
 * a missed cron can be replayed by hand:
 *   pnpm exec convex run forecasts:captureSnapshots '{}' --prod
 */
export const captureSnapshots = internalMutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now()
    const snapshotMonth = monthKey(now)
    const orgs = await ctx.db.query('organizations').collect()

    let captured = 0
    let skipped = 0
    for (const org of orgs) {
      const existing = await ctx.db
        .query('forecastSnapshots')
        .withIndex('by_org_month', (q) =>
          q.eq('orgId', org._id).eq('snapshotMonth', snapshotMonth),
        )
        .unique()
      if (existing) {
        skipped += 1
        continue
      }
      const grid = await computeForecastGridForOrg(
        ctx,
        org._id,
        0,
        SNAPSHOT_HORIZON_MONTHS,
      )
      await ctx.db.insert('forecastSnapshots', {
        orgId: org._id,
        snapshotMonth,
        capturedAt: now,
        startingBalanceCents: grid.startingBalanceCents,
        months: grid.projection.map((point) => ({
          monthKey: point.monthKey,
          committedBalanceCents: point.committedBalanceCents,
          plannedBalanceCents: point.plannedBalanceCents,
        })),
      })
      captured += 1
    }
    return { captured, skipped }
  },
})

/**
 * Forecast reliability of the LAST month: what the 1st-of-month snapshot
 * projected for its end (planned scenario) vs the real end-of-month balance
 * rebuilt from the transactions. Null until a snapshot of that month exists
 * (the first one lands one month after phase 4b ships).
 */
export const getForecastReliability = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)
    const now = Date.now()
    const nowDate = new Date(now)
    const currentMonthStart = Date.UTC(
      nowDate.getUTCFullYear(),
      nowDate.getUTCMonth(),
      1,
    )
    const prevMonthKey = monthKey(addMonthsUtc(currentMonthStart, -1))

    const snapshot = await ctx.db
      .query('forecastSnapshots')
      .withIndex('by_org_month', (q) =>
        q.eq('orgId', orgId).eq('snapshotMonth', prevMonthKey),
      )
      .unique()
    const projected = snapshot?.months.find((m) => m.monthKey === prevMonthKey)
    if (!snapshot || !projected) return null

    // Real end-of-month balance, rebuilt backwards from the CURRENT
    // available balance (same scope as the projection's starting balance).
    const accounts = await ctx.db
      .query('bankAccounts')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()
    const currentBalanceCents = accounts
      .filter((a) => isAvailableAccount(a) && a.currency === 'EUR')
      .reduce((sum, a) => sum + (a.currentBalance ?? 0), 0)
    const history = await computeCashHistoryForOrgs(
      ctx,
      [orgId],
      1,
      currentBalanceCents,
    )
    const actual = history.find((p) => p.monthKey === prevMonthKey)
    if (!actual) return null

    return {
      monthKey: prevMonthKey,
      projectedCents: projected.plannedBalanceCents,
      actualCents: actual.balanceCents,
      deltaCents: actual.balanceCents - projected.plannedBalanceCents,
    }
  },
})

/** The org's threshold-alert setting (null = never configured). */
export const getCashAlert = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)
    return await ctx.db
      .query('cashAlertSettings')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .unique()
  },
})

/**
 * Creates/updates the org's threshold alert. Any change clears the
 * notification cooldown so the new threshold can fire immediately.
 */
export const setCashAlert = mutation({
  args: {
    orgId: v.id('organizations'),
    thresholdCents: v.number(),
    active: v.boolean(),
  },
  handler: async (ctx, { orgId, thresholdCents, active }) => {
    const { user } = await requireOrgMember(ctx, orgId)
    if (!Number.isInteger(thresholdCents) || thresholdCents < 0) {
      throw new ConvexError('invalid_amount')
    }
    const existing = await ctx.db
      .query('cashAlertSettings')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .unique()
    if (existing) {
      await ctx.db.patch('cashAlertSettings', existing._id, {
        thresholdCents,
        active,
        lastNotifiedAt: undefined,
        updatedBy: user._id,
      })
      return null
    }
    await ctx.db.insert('cashAlertSettings', {
      orgId,
      thresholdCents,
      active,
      updatedBy: user._id,
    })
    return null
  },
})

/**
 * Daily threshold-alert evaluation (cron, 07:00 UTC — convex/crons.ts, no
 * auth like captureSnapshots). Breach = the available balance or any
 * projected month over the next 3 months (planned scenario) under the
 * threshold → email to every org member, then 7-day cooldown.
 */
export const checkCashAlerts = internalMutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now()
    const siteUrl = process.env.SITE_URL ?? ''
    const settings = await ctx.db.query('cashAlertSettings').collect()

    let notified = 0
    for (const setting of settings) {
      if (!setting.active) continue
      if (
        setting.lastNotifiedAt !== undefined &&
        now - setting.lastNotifiedAt < ALERT_COOLDOWN_MS
      ) {
        continue
      }
      const grid = await computeForecastGridForOrg(
        ctx,
        setting.orgId,
        0,
        ALERT_HORIZON_MONTHS,
      )
      const minProjectedCents = Math.min(
        grid.startingBalanceCents,
        ...grid.projection.map((point) => point.plannedBalanceCents),
      )
      if (minProjectedCents >= setting.thresholdCents) continue

      const org = await ctx.db.get('organizations', setting.orgId)
      if (!org) continue
      const members = await ctx.db
        .query('organizationMembers')
        .withIndex('by_org', (q) => q.eq('orgId', setting.orgId))
        .collect()
      for (const member of members) {
        const user = await ctx.db.get('users', member.userId)
        if (!user?.email) continue
        const { subject, html, text } = cashAlertEmail({
          locale: user.preferredLanguage === 'fr' ? 'fr' : 'en',
          orgName: org.name,
          thresholdCents: setting.thresholdCents,
          minProjectedCents,
          cashUrl: `${siteUrl}/app/${org.slug}/cash`,
        })
        await resend.sendEmail(ctx, {
          from: RESEND_FROM,
          to: user.email,
          subject,
          html,
          text,
        })
      }
      await ctx.db.patch('cashAlertSettings', setting._id, {
        lastNotifiedAt: now,
      })
      notified += 1
    }
    return { notified }
  },
})

/** Idempotency key of the quarterly VAT entry suggestion. */
function vatDerivedKey(orgId: Id<'organizations'>, quarterKey: string): string {
  return `vat:${orgId}:${quarterKey}`
}

/**
 * Quarterly VAT entry suggestion: the net VAT of the last CLOSED civil
 * quarter, when it is OWED (collected > deductible), proposed as a
 * committed `taxes` outflow due on the 24th of the month after the quarter.
 * Null when nothing is owed or the entry was already created (idempotent
 * via derivedKey "vat:{orgId}:{quarter}"). Like the suggested rules, this
 * never writes on its own — creation is the explicit gesture below.
 */
export const suggestVatEntry = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)
    const quarter = previousQuarter(Date.now())

    const existing = await ctx.db
      .query('forecastEntries')
      .withIndex('by_derivedKey', (q) =>
        q.eq('derivedKey', vatDerivedKey(orgId, quarter.quarterKey)),
      )
      .unique()
    if (existing) return null

    const position = await computeVatPositionForOrg(ctx, orgId, {
      startMs: quarter.startMs,
      endMs: quarter.endMs,
    })
    // Owed to the state = collected − deductible (the opposite sign of the
    // "recoverable VAT" card).
    const owedCents = position.collectedCents - position.deductibleCents
    if (owedCents <= 0) return null

    return {
      quarterKey: quarter.quarterKey,
      dueDateMs: quarter.dueDateMs,
      owedCents,
      deductibleCents: position.deductibleCents,
      collectedCents: position.collectedCents,
      unqualifiedCount: position.unqualifiedCount,
    }
  },
})

/**
 * Creates the suggested quarterly VAT entry (committed `taxes` outflow due
 * the 24th after the quarter). The amount is recomputed server-side —
 * only the user-facing label comes from the client (i18n). Idempotent by
 * derivedKey; the entry then lives like any one-off (editable/cancellable,
 * never touched by expandRules).
 */
export const createVatEntry = mutation({
  args: { orgId: v.id('organizations'), label: v.string() },
  handler: async (ctx, { orgId, label }) => {
    await requireOrgMember(ctx, orgId)
    const quarter = previousQuarter(Date.now())
    const derivedKey = vatDerivedKey(orgId, quarter.quarterKey)

    const existing = await ctx.db
      .query('forecastEntries')
      .withIndex('by_derivedKey', (q) => q.eq('derivedKey', derivedKey))
      .unique()
    if (existing) throw new ConvexError('already_exists')

    const position = await computeVatPositionForOrg(ctx, orgId, {
      startMs: quarter.startMs,
      endMs: quarter.endMs,
    })
    const owedCents = position.collectedCents - position.deductibleCents
    if (owedCents <= 0) throw new ConvexError('nothing_due')

    return await ctx.db.insert('forecastEntries', {
      orgId,
      date: quarter.dueDateMs,
      amountCents: owedCents,
      direction: 'out',
      confidence: 'confirmed',
      status: 'pending',
      label,
      category: 'taxes',
      derivedKey,
      overridden: false,
      currency: 'EUR',
    })
  },
})
