/**
 * Cash flow forecast — deterministic projection layer.
 *
 * - `forecastRules`: recurring causes (SCI rent, salaries, installments…).
 * - `forecastEntries`: dated occurrences, generated by `expandRules`
 *   (idempotent via `derivedKey`) or created by hand.
 *
 * Safe regeneration: a derived entry edited by hand (`overridden: true`)
 * or already realized/cancelled is NEVER rewritten by `expandRules`.
 * The date-math lives in convex/lib/recurrence.ts (pure, tested by
 * tests/recurrence.test.ts).
 */

import { ConvexError, v } from 'convex/values'
import { mutation, query } from './_generated/server'
import { requireAppUser, requireOrgMember } from './lib/auth'
import {
  addMonthsUtc,
  buildMonthlyBalance,
  buildMonthlyHistory,
  entryUpsertAction,
  expandOccurrences,
  ruleDerivedKey,
} from './lib/recurrence'
import type { HistoryTx } from './lib/recurrence'
import type { DataModel, Doc, Id } from './_generated/dataModel'
import type { GenericMutationCtx, GenericQueryCtx } from 'convex/server'

// Local validators (deals.ts pattern) — keep aligned with schema.ts.
const directionValidator = v.union(v.literal('in'), v.literal('out'))

const frequencyValidator = v.union(
  v.literal('weekly'),
  v.literal('monthly'),
  v.literal('quarterly'),
  v.literal('yearly'),
)

const confidenceValidator = v.union(
  v.literal('confirmed'),
  v.literal('expected'),
  v.literal('probable'),
)

// Upper bound on the projection horizon (10 years), guardrail against an
// oversized expansion in a single mutation.
const MAX_HORIZON_MONTHS = 120

export function assertValidHorizon(horizonMonths: number) {
  if (
    !Number.isInteger(horizonMonths) ||
    horizonMonths < 1 ||
    horizonMonths > MAX_HORIZON_MONTHS
  ) {
    throw new ConvexError('invalid_horizon')
  }
}

/**
 * Resolves the org scope: `orgId` provided → that org (membership
 * required); absent → all orgs the user is a member of
 * (convex/aggregate.ts pattern).
 */
async function resolveOrgScope(
  ctx: GenericQueryCtx<DataModel> | GenericMutationCtx<DataModel>,
  orgId: Id<'organizations'> | undefined,
): Promise<Array<Id<'organizations'>>> {
  if (orgId) {
    await requireOrgMember(ctx, orgId)
    return [orgId]
  }
  const user = await requireAppUser(ctx)
  const memberships = await ctx.db
    .query('organizationMembers')
    .withIndex('by_user', (q) => q.eq('userId', user._id))
    .collect()
  return memberships.map((m) => m.orgId)
}

// ─── Rule field validation ──────────────────────────────────────────────────

function assertValidRuleFields(rule: {
  amountCents: number
  frequency: 'weekly' | 'monthly' | 'quarterly' | 'yearly'
  interval: number
  anchorDay: number
  startDate: number
  endDate?: number
}) {
  // Strictly positive integer cents — no monetary floats.
  if (!Number.isInteger(rule.amountCents) || rule.amountCents <= 0) {
    throw new ConvexError('invalid_amount')
  }
  if (!Number.isInteger(rule.interval) || rule.interval < 1) {
    throw new ConvexError('invalid_interval')
  }
  const maxAnchor = rule.frequency === 'weekly' ? 7 : 31
  if (
    !Number.isInteger(rule.anchorDay) ||
    rule.anchorDay < 1 ||
    rule.anchorDay > maxAnchor
  ) {
    throw new ConvexError('invalid_anchor_day')
  }
  if (rule.endDate !== undefined && rule.endDate < rule.startDate) {
    throw new ConvexError('invalid_date_range')
  }
}

// ─── Rules ───────────────────────────────────────────────────────────────────

/**
 * Rule insertion (validation included) — core shared between the public
 * mutation and the agent tool (convex/agentToolsForecasts.ts).
 * The caller has already verified org membership.
 */
export async function insertRule(
  ctx: GenericMutationCtx<DataModel>,
  args: {
    orgId: Id<'organizations'>
    label: string
    amountCents: number
    direction: 'in' | 'out'
    category?: string
    frequency: 'weekly' | 'monthly' | 'quarterly' | 'yearly'
    interval?: number
    anchorDay: number
    startDate: number
    endDate?: number
    active?: boolean
  },
): Promise<Id<'forecastRules'>> {
  const interval = args.interval ?? 1
  assertValidRuleFields({ ...args, interval })
  return await ctx.db.insert('forecastRules', {
    orgId: args.orgId,
    label: args.label,
    amountCents: args.amountCents,
    direction: args.direction,
    category: args.category,
    frequency: args.frequency,
    interval,
    anchorDay: args.anchorDay,
    startDate: args.startDate,
    endDate: args.endDate,
    active: args.active ?? true,
    sourceType: 'manual',
  })
}

/** Creates a recurring rule (e.g. monthly SCI rent) in an org. */
export const createRule = mutation({
  args: {
    orgId: v.id('organizations'),
    label: v.string(),
    amountCents: v.number(),
    direction: directionValidator,
    category: v.optional(v.string()),
    frequency: frequencyValidator,
    interval: v.optional(v.number()), // default 1
    anchorDay: v.number(),
    startDate: v.number(),
    endDate: v.optional(v.number()),
    active: v.optional(v.boolean()), // default true
  },
  handler: async (ctx, args) => {
    await requireOrgMember(ctx, args.orgId)
    return await insertRule(ctx, args)
  },
})

/** An org's rules (forecast UI), sorted by label. */
export const listRules = query({
  args: { orgId: v.id('organizations') },
  handler: async (ctx, { orgId }) => {
    await requireOrgMember(ctx, orgId)
    const rules = await ctx.db
      .query('forecastRules')
      .withIndex('by_org', (q) => q.eq('orgId', orgId))
      .collect()
    rules.sort((a, b) => a.label.localeCompare(b.label))
    return rules
  },
})

/**
 * Deletes a rule AND its still-untouched derived entries (pending, not
 * overridden). Realized / cancelled / hand-edited entries are kept —
 * that's history, not projection.
 */
export const deleteRule = mutation({
  args: { ruleId: v.id('forecastRules') },
  handler: async (ctx, { ruleId }) => {
    const rule = await ctx.db.get('forecastRules', ruleId)
    if (!rule) throw new ConvexError('not_found')
    await requireOrgMember(ctx, rule.orgId)

    const entries = await ctx.db
      .query('forecastEntries')
      .withIndex('by_rule', (q) => q.eq('ruleId', ruleId))
      .collect()
    let entriesRemoved = 0
    for (const entry of entries) {
      if (entry.status === 'pending' && !entry.overridden) {
        await ctx.db.delete('forecastEntries', entry._id)
        entriesRemoved += 1
      }
    }
    await ctx.db.delete('forecastRules', ruleId)
    return { entriesRemoved }
  },
})

/**
 * Updates a rule. Does not affect already-generated entries: re-run
 * `expandRules` to resync the unprotected occurrences.
 */
export const updateRule = mutation({
  args: {
    ruleId: v.id('forecastRules'),
    patch: v.object({
      label: v.optional(v.string()),
      amountCents: v.optional(v.number()),
      direction: v.optional(directionValidator),
      category: v.optional(v.string()),
      frequency: v.optional(frequencyValidator),
      interval: v.optional(v.number()),
      anchorDay: v.optional(v.number()),
      startDate: v.optional(v.number()),
      endDate: v.optional(v.number()),
      active: v.optional(v.boolean()),
    }),
  },
  handler: async (ctx, { ruleId, patch }) => {
    const rule = await ctx.db.get('forecastRules', ruleId)
    if (!rule) throw new ConvexError('not_found')
    await requireOrgMember(ctx, rule.orgId)
    assertValidRuleFields({ ...rule, ...patch })
    await ctx.db.patch('forecastRules', ruleId, patch)
    return null
  },
})

// ─── Rule → occurrence expansion ─────────────────────────────────────────────

/**
 * Expands active rules into `forecastEntries` over `horizonMonths` months,
 * from max(startDate, now) to now + horizon. Idempotent: upsert by
 * `derivedKey` ("rule:{ruleId}:{YYYY-MM-DD}").
 *
 * - Missing entry → created (confidence `confirmed`, status `pending`).
 * - Existing unprotected entry → resync amount/label/category/direction.
 * - Protected entry (overridden, realized or cancelled) → SKIP.
 *
 * Without `orgId`: all orgs the user is a member of.
 */
export const expandRules = mutation({
  args: {
    orgId: v.optional(v.id('organizations')),
    horizonMonths: v.number(),
  },
  handler: async (ctx, { orgId, horizonMonths }) => {
    assertValidHorizon(horizonMonths)
    const orgIds = await resolveOrgScope(ctx, orgId)
    return await expandRulesForOrgs(ctx, orgIds, horizonMonths)
  },
})

/**
 * Expansion core (no auth) — shared between the public mutation and the
 * agent tool. The caller has already verified membership of the orgs.
 */
export async function expandRulesForOrgs(
  ctx: GenericMutationCtx<DataModel>,
  orgIds: Array<Id<'organizations'>>,
  horizonMonths: number,
) {
  const now = Date.now()
  const horizonEnd = addMonthsUtc(now, horizonMonths)

  let rulesProcessed = 0
  let created = 0
  let updated = 0
  let skippedProtected = 0

  for (const oid of orgIds) {
    const rules = await ctx.db
      .query('forecastRules')
      .withIndex('by_org', (q) => q.eq('orgId', oid))
      .collect()

    for (const rule of rules) {
      if (!rule.active) continue
      rulesProcessed += 1

      const occurrences = expandOccurrences(
        rule,
        Math.max(rule.startDate, now),
        horizonEnd,
      )

      for (const occurrence of occurrences) {
        const derivedKey = ruleDerivedKey(rule._id, occurrence)
        const existing = await ctx.db
          .query('forecastEntries')
          .withIndex('by_derivedKey', (q) => q.eq('derivedKey', derivedKey))
          .unique()

        // The create/update/skip decision is pure and tested in
        // tests/recurrence.test.ts — only the DB glue lives here.
        if (existing === null) {
          await ctx.db.insert('forecastEntries', {
            orgId: oid,
            date: occurrence,
            amountCents: rule.amountCents,
            direction: rule.direction,
            confidence: 'confirmed',
            status: 'pending',
            label: rule.label,
            category: rule.category,
            ruleId: rule._id,
            derivedKey,
            overridden: false,
            currency: 'EUR',
          })
          created += 1
        } else if (entryUpsertAction(existing) === 'skip') {
          skippedProtected += 1
        } else {
          // Resync from the rule (the date is frozen by the derivedKey).
          await ctx.db.patch('forecastEntries', existing._id, {
            amountCents: rule.amountCents,
            direction: rule.direction,
            label: rule.label,
            category: rule.category,
          })
          updated += 1
        }
      }
    }
  }

  return { rulesProcessed, created, updated, skippedProtected }
}

// ─── Projected balance ───────────────────────────────────────────────────────

/**
 * Projected cash balance, aggregated BY MONTH over `horizonMonths` months.
 *
 * - Starting balance = sum of the real `bankAccounts.currentBalance`
 *   (non-archived EUR accounts) across the in-scope orgs.
 * - Monthly flow = sum of the month's `pending` `forecastEntries` (from the
 *   start of the current month to now + horizon), filtered by
 *   `minConfidence` (`confirmed` = committed only; `expected` = committed +
 *   expected; absent = everything).
 * - Only EUR is aggregated; non-EUR accounts/entries are counted in
 *   `ignoredNonEur*` for visibility.
 *
 * Without `orgId`: consolidated over all orgs the user is a member of.
 *
 * `historyMonths` (optional) adds `history`: the real end-of-month balance
 * for the last N months, rebuilt backwards from the current balance and the
 * EUR accounts' transactions — the real → projected junction of the curve.
 */
export const getForecastBalance = query({
  args: {
    orgId: v.optional(v.id('organizations')),
    horizonMonths: v.number(),
    minConfidence: v.optional(confidenceValidator),
    historyMonths: v.optional(v.number()),
  },
  handler: async (
    ctx,
    { orgId, horizonMonths, minConfidence, historyMonths },
  ) => {
    assertValidHorizon(horizonMonths)
    const orgIds = await resolveOrgScope(ctx, orgId)
    const balance = await computeForecastBalanceForOrgs(
      ctx,
      orgIds,
      horizonMonths,
      minConfidence,
    )
    if (!historyMonths) return { ...balance, history: null }

    assertValidHorizon(historyMonths)
    const history = await computeCashHistoryForOrgs(
      ctx,
      orgIds,
      historyMonths,
      balance.startingBalanceCents,
    )
    return { ...balance, history }
  },
})

/**
 * Real end-of-month balance for the last `monthsBack` months (non-archived
 * EUR accounts only, same scope as the projected starting balance). The
 * backwards computation is pure (convex/lib/recurrence.ts:buildMonthlyHistory).
 */
async function computeCashHistoryForOrgs(
  ctx: GenericQueryCtx<DataModel>,
  orgIds: Array<Id<'organizations'>>,
  monthsBack: number,
  currentBalanceCents: number,
) {
  const now = Date.now()
  const nowDate = new Date(now)
  const windowStart = addMonthsUtc(
    Date.UTC(nowDate.getUTCFullYear(), nowDate.getUTCMonth(), 1),
    -monthsBack,
  )

  const transactions: Array<HistoryTx> = []
  for (const oid of orgIds) {
    const accounts = await ctx.db
      .query('bankAccounts')
      .withIndex('by_org', (q) => q.eq('orgId', oid))
      .collect()
    const eurAccountIds = new Set(
      accounts
        .filter((a) => !a.archivedAt && a.currency === 'EUR')
        .map((a) => a._id),
    )
    const txs = await ctx.db
      .query('transactions')
      .withIndex('by_org_date', (q) =>
        q.eq('orgId', oid).gte('transactionDate', windowStart).lte(
          'transactionDate',
          now,
        ),
      )
      .collect()
    for (const tx of txs) {
      if (!eurAccountIds.has(tx.bankAccountId)) continue
      transactions.push({
        transactionDate: tx.transactionDate,
        amountCents: tx.amount,
        direction: tx.direction,
      })
    }
  }

  return buildMonthlyHistory({
    transactions,
    currentBalanceCents,
    monthsBack,
    now,
  })
}

/**
 * Projected-balance core (no auth) — shared between the public query and
 * the agent tool. The caller has already verified membership of the orgs.
 */
export async function computeForecastBalanceForOrgs(
  ctx: GenericQueryCtx<DataModel>,
  orgIds: Array<Id<'organizations'>>,
  horizonMonths: number,
  minConfidence?: 'confirmed' | 'expected' | 'probable',
) {
  const now = Date.now()
  const nowDate = new Date(now)
  // Window: from the 1st of the current month (the month's still-pending
  // entries count toward the trajectory) to now + horizon.
  const windowStart = Date.UTC(
    nowDate.getUTCFullYear(),
    nowDate.getUTCMonth(),
    1,
  )
  const windowEnd = addMonthsUtc(now, horizonMonths)

  // 1. Starting balance = current real balances (Powens) of EUR accounts.
  let startingBalanceCents = 0
  let ignoredNonEurAccounts = 0
  for (const oid of orgIds) {
    const accounts = await ctx.db
      .query('bankAccounts')
      .withIndex('by_org', (q) => q.eq('orgId', oid))
      .collect()
    for (const account of accounts) {
      if (account.archivedAt) continue
      if (account.currency !== 'EUR') {
        ignoredNonEurAccounts += 1
        continue
      }
      startingBalanceCents += account.currentBalance ?? 0
    }
  }

  // 2. In-scope forecast entries within the window.
  // TODO(inter-entity netting): in consolidated mode (orgId absent),
  // exclude entries whose `counterpartyOrgId` belongs to `orgIds`
  // (intra-group flows). Field exists in the schema, not read in the MVP.
  const entries: Array<Doc<'forecastEntries'>> = []
  for (const oid of orgIds) {
    const orgEntries = await ctx.db
      .query('forecastEntries')
      .withIndex('by_org_and_date', (q) =>
        q.eq('orgId', oid).gte('date', windowStart).lte('date', windowEnd),
      )
      .collect()
    // Skip entries flagged `dateMissing` (deal-derived without a known date):
    // their `date` is a placeholder, they must not weigh on the projection.
    entries.push(...orgEntries.filter((e) => !e.dateMissing))
  }

  // 3. Pure monthly aggregation (tested in tests/recurrence.test.ts).
  const { months, ignoredNonEurEntries } = buildMonthlyBalance({
    entries,
    startingBalanceCents,
    windowStart,
    windowEnd,
    minConfidence,
  })

  return {
    startingBalanceCents,
    currency: 'EUR',
    ignoredNonEurAccounts,
    ignoredNonEurEntries,
    months,
  }
}

// ─── Forecast → realized matching ────────────────────────────────────────────

/**
 * Marks an entry as realized by attaching it to a real transaction in the
 * same org (modeled on transactions.ts:matchTransaction). Does not touch the
 * transaction itself: the transaction → deal matching (matchStatus,
 * reconciled) stays exclusively managed by convex/transactions.ts.
 */
export const markEntryRealized = mutation({
  args: {
    entryId: v.id('forecastEntries'),
    transactionId: v.id('transactions'),
  },
  handler: async (ctx, { entryId, transactionId }) => {
    const entry = await ctx.db.get('forecastEntries', entryId)
    if (!entry) throw new ConvexError('not_found')
    await requireOrgMember(ctx, entry.orgId)

    const tx = await ctx.db.get('transactions', transactionId)
    if (!tx || tx.orgId !== entry.orgId) {
      throw new ConvexError('transaction_wrong_org')
    }

    await ctx.db.patch('forecastEntries', entry._id, {
      status: 'realized',
      realizedTransactionId: transactionId,
    })
    return null
  },
})

// ─── Manual entry CRUD ───────────────────────────────────────────────────────

/** Creates a 100% manual entry (no rule, no derivedKey). */
export const createManualEntry = mutation({
  args: {
    orgId: v.id('organizations'),
    date: v.number(),
    amountCents: v.number(),
    direction: directionValidator,
    confidence: confidenceValidator,
    label: v.string(),
    category: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    await requireOrgMember(ctx, args.orgId)
    if (!Number.isInteger(args.amountCents) || args.amountCents <= 0) {
      throw new ConvexError('invalid_amount')
    }
    return await ctx.db.insert('forecastEntries', {
      orgId: args.orgId,
      date: args.date,
      amountCents: args.amountCents,
      direction: args.direction,
      confidence: args.confidence,
      status: 'pending',
      label: args.label,
      category: args.category,
      overridden: false,
      currency: 'EUR',
    })
  },
})

/**
 * Edits an entry. If it is derived from a rule (`ruleId` non null), it
 * becomes `overridden: true`: expandRules will never rewrite it again.
 */
export const updateEntry = mutation({
  args: {
    entryId: v.id('forecastEntries'),
    patch: v.object({
      date: v.optional(v.number()),
      amountCents: v.optional(v.number()),
      direction: v.optional(directionValidator),
      confidence: v.optional(confidenceValidator),
      label: v.optional(v.string()),
      category: v.optional(v.string()),
    }),
  },
  handler: async (ctx, { entryId, patch }) => {
    const entry = await ctx.db.get('forecastEntries', entryId)
    if (!entry) throw new ConvexError('not_found')
    await requireOrgMember(ctx, entry.orgId)
    if (
      patch.amountCents !== undefined &&
      (!Number.isInteger(patch.amountCents) || patch.amountCents <= 0)
    ) {
      throw new ConvexError('invalid_amount')
    }
    await ctx.db.patch('forecastEntries', entry._id, {
      ...patch,
      // A hand-edited derived entry becomes protected from regeneration.
      ...(entry.ruleId ? { overridden: true } : {}),
      // Setting a real date re-activates a deal-derived `dateMissing` entry
      // (it now counts toward the projected balance again).
      ...(patch.date !== undefined ? { dateMissing: false } : {}),
    })
    return null
  },
})

/** Cancels an entry: it no longer counts toward the projected balance. */
export const cancelEntry = mutation({
  args: { entryId: v.id('forecastEntries') },
  handler: async (ctx, { entryId }) => {
    const entry = await ctx.db.get('forecastEntries', entryId)
    if (!entry) throw new ConvexError('not_found')
    await requireOrgMember(ctx, entry.orgId)
    await ctx.db.patch('forecastEntries', entry._id, { status: 'cancelled' })
    return null
  },
})
