/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppMeRouteImport } from './routes/app/me'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as AppAllRouteRouteImport } from './routes/app/all/route'
import { Route as AppOrgSlugRouteRouteImport } from './routes/app/$orgSlug/route'
import { Route as AppAllIndexRouteImport } from './routes/app/all/index'
import { Route as AppOrgSlugIndexRouteImport } from './routes/app/$orgSlug/index'
import { Route as AppAllReportsRouteImport } from './routes/app/all/reports'
import { Route as AppAllParticipationsRouteImport } from './routes/app/all/participations'
import { Route as AppAllDealsRouteImport } from './routes/app/all/deals'
import { Route as AppOrgSlugTodoRouteImport } from './routes/app/$orgSlug/todo'
import { Route as AppOrgSlugChangelogRouteImport } from './routes/app/$orgSlug/changelog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrgSlugSettingsRouteRouteImport } from './routes/app/$orgSlug/settings/route'
import { Route as AppOrgSlugSettingsIndexRouteImport } from './routes/app/$orgSlug/settings/index'
import { Route as AppOrgSlugPointageIndexRouteImport } from './routes/app/$orgSlug/pointage.index'
import { Route as AppOrgSlugPassifIndexRouteImport } from './routes/app/$orgSlug/passif.index'
import { Route as AppOrgSlugParticipationsIndexRouteImport } from './routes/app/$orgSlug/participations.index'
import { Route as AppOrgSlugDealsIndexRouteImport } from './routes/app/$orgSlug/deals.index'
import { Route as AppOrgSlugCashIndexRouteImport } from './routes/app/$orgSlug/cash.index'
import { Route as AppOrgSlugSettingsMembersRouteImport } from './routes/app/$orgSlug/settings/members'
import { Route as AppOrgSlugSettingsInvitationsRouteImport } from './routes/app/$orgSlug/settings/invitations'
import { Route as AppOrgSlugSettingsIntegrationsRouteImport } from './routes/app/$orgSlug/settings/integrations'
import { Route as AppOrgSlugSettingsGeneralRouteImport } from './routes/app/$orgSlug/settings/general'
import { Route as AppOrgSlugParticipationsCompanyIdRouteImport } from './routes/app/$orgSlug/participations.$companyId'
import { Route as AppOrgSlugDealsDealIdRouteImport } from './routes/app/$orgSlug/deals.$dealId'
import { Route as AppOrgSlugCashAccountIdRouteImport } from './routes/app/$orgSlug/cash.$accountId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAllRouteRoute = AppAllRouteRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrgSlugRouteRoute = AppOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAllIndexRoute = AppAllIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAllRouteRoute,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppAllReportsRoute = AppAllReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAllRouteRoute,
} as any)
const AppAllParticipationsRoute = AppAllParticipationsRouteImport.update({
  id: '/participations',
  path: '/participations',
  getParentRoute: () => AppAllRouteRoute,
} as any)
const AppAllDealsRoute = AppAllDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppAllRouteRoute,
} as any)
const AppOrgSlugTodoRoute = AppOrgSlugTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugChangelogRoute = AppOrgSlugChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugSettingsRouteRoute = AppOrgSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugSettingsIndexRoute = AppOrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugSettingsRouteRoute,
} as any)
const AppOrgSlugPointageIndexRoute = AppOrgSlugPointageIndexRouteImport.update({
  id: '/pointage/',
  path: '/pointage/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugPassifIndexRoute = AppOrgSlugPassifIndexRouteImport.update({
  id: '/passif/',
  path: '/passif/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugParticipationsIndexRoute =
  AppOrgSlugParticipationsIndexRouteImport.update({
    id: '/participations/',
    path: '/participations/',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugDealsIndexRoute = AppOrgSlugDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugCashIndexRoute = AppOrgSlugCashIndexRouteImport.update({
  id: '/cash/',
  path: '/cash/',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugSettingsMembersRoute =
  AppOrgSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugSettingsInvitationsRoute =
  AppOrgSlugSettingsInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugSettingsIntegrationsRoute =
  AppOrgSlugSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugSettingsGeneralRoute =
  AppOrgSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AppOrgSlugSettingsRouteRoute,
  } as any)
const AppOrgSlugParticipationsCompanyIdRoute =
  AppOrgSlugParticipationsCompanyIdRouteImport.update({
    id: '/participations/$companyId',
    path: '/participations/$companyId',
    getParentRoute: () => AppOrgSlugRouteRoute,
  } as any)
const AppOrgSlugDealsDealIdRoute = AppOrgSlugDealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugCashAccountIdRoute = AppOrgSlugCashAccountIdRouteImport.update({
  id: '/cash/$accountId',
  path: '/cash/$accountId',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/app/all': typeof AppAllRouteRouteWithChildren
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/app/$orgSlug/todo': typeof AppOrgSlugTodoRoute
  '/app/all/deals': typeof AppAllDealsRoute
  '/app/all/participations': typeof AppAllParticipationsRoute
  '/app/all/reports': typeof AppAllReportsRoute
  '/app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/app/all/': typeof AppAllIndexRoute
  '/app/$orgSlug/cash/$accountId': typeof AppOrgSlugCashAccountIdRoute
  '/app/$orgSlug/deals/$dealId': typeof AppOrgSlugDealsDealIdRoute
  '/app/$orgSlug/participations/$companyId': typeof AppOrgSlugParticipationsCompanyIdRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/integrations': typeof AppOrgSlugSettingsIntegrationsRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/cash/': typeof AppOrgSlugCashIndexRoute
  '/app/$orgSlug/deals/': typeof AppOrgSlugDealsIndexRoute
  '/app/$orgSlug/participations/': typeof AppOrgSlugParticipationsIndexRoute
  '/app/$orgSlug/passif/': typeof AppOrgSlugPassifIndexRoute
  '/app/$orgSlug/pointage/': typeof AppOrgSlugPointageIndexRoute
  '/app/$orgSlug/settings/': typeof AppOrgSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/app/$orgSlug/todo': typeof AppOrgSlugTodoRoute
  '/app/all/deals': typeof AppAllDealsRoute
  '/app/all/participations': typeof AppAllParticipationsRoute
  '/app/all/reports': typeof AppAllReportsRoute
  '/app/$orgSlug': typeof AppOrgSlugIndexRoute
  '/app/all': typeof AppAllIndexRoute
  '/app/$orgSlug/cash/$accountId': typeof AppOrgSlugCashAccountIdRoute
  '/app/$orgSlug/deals/$dealId': typeof AppOrgSlugDealsDealIdRoute
  '/app/$orgSlug/participations/$companyId': typeof AppOrgSlugParticipationsCompanyIdRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/integrations': typeof AppOrgSlugSettingsIntegrationsRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/cash': typeof AppOrgSlugCashIndexRoute
  '/app/$orgSlug/deals': typeof AppOrgSlugDealsIndexRoute
  '/app/$orgSlug/participations': typeof AppOrgSlugParticipationsIndexRoute
  '/app/$orgSlug/passif': typeof AppOrgSlugPassifIndexRoute
  '/app/$orgSlug/pointage': typeof AppOrgSlugPointageIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/app/all': typeof AppAllRouteRouteWithChildren
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/admin': typeof AppAdminRoute
  '/app/me': typeof AppMeRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$orgSlug/changelog': typeof AppOrgSlugChangelogRoute
  '/app/$orgSlug/todo': typeof AppOrgSlugTodoRoute
  '/app/all/deals': typeof AppAllDealsRoute
  '/app/all/participations': typeof AppAllParticipationsRoute
  '/app/all/reports': typeof AppAllReportsRoute
  '/app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/app/all/': typeof AppAllIndexRoute
  '/app/$orgSlug/cash/$accountId': typeof AppOrgSlugCashAccountIdRoute
  '/app/$orgSlug/deals/$dealId': typeof AppOrgSlugDealsDealIdRoute
  '/app/$orgSlug/participations/$companyId': typeof AppOrgSlugParticipationsCompanyIdRoute
  '/app/$orgSlug/settings/general': typeof AppOrgSlugSettingsGeneralRoute
  '/app/$orgSlug/settings/integrations': typeof AppOrgSlugSettingsIntegrationsRoute
  '/app/$orgSlug/settings/invitations': typeof AppOrgSlugSettingsInvitationsRoute
  '/app/$orgSlug/settings/members': typeof AppOrgSlugSettingsMembersRoute
  '/app/$orgSlug/cash/': typeof AppOrgSlugCashIndexRoute
  '/app/$orgSlug/deals/': typeof AppOrgSlugDealsIndexRoute
  '/app/$orgSlug/participations/': typeof AppOrgSlugParticipationsIndexRoute
  '/app/$orgSlug/passif/': typeof AppOrgSlugPassifIndexRoute
  '/app/$orgSlug/pointage/': typeof AppOrgSlugPointageIndexRoute
  '/app/$orgSlug/settings/': typeof AppOrgSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/$orgSlug'
    | '/app/all'
    | '/.well-known/oauth-authorization-server'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/app/'
    | '/app/$orgSlug/settings'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/app/$orgSlug/todo'
    | '/app/all/deals'
    | '/app/all/participations'
    | '/app/all/reports'
    | '/app/$orgSlug/'
    | '/app/all/'
    | '/app/$orgSlug/cash/$accountId'
    | '/app/$orgSlug/deals/$dealId'
    | '/app/$orgSlug/participations/$companyId'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/integrations'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/cash/'
    | '/app/$orgSlug/deals/'
    | '/app/$orgSlug/participations/'
    | '/app/$orgSlug/passif/'
    | '/app/$orgSlug/pointage/'
    | '/app/$orgSlug/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/.well-known/oauth-authorization-server'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/app'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/app/$orgSlug/todo'
    | '/app/all/deals'
    | '/app/all/participations'
    | '/app/all/reports'
    | '/app/$orgSlug'
    | '/app/all'
    | '/app/$orgSlug/cash/$accountId'
    | '/app/$orgSlug/deals/$dealId'
    | '/app/$orgSlug/participations/$companyId'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/integrations'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/cash'
    | '/app/$orgSlug/deals'
    | '/app/$orgSlug/participations'
    | '/app/$orgSlug/passif'
    | '/app/$orgSlug/pointage'
    | '/app/$orgSlug/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/$orgSlug'
    | '/app/all'
    | '/.well-known/oauth-authorization-server'
    | '/accept-invite/$token'
    | '/app/admin'
    | '/app/me'
    | '/app/onboarding'
    | '/app/'
    | '/app/$orgSlug/settings'
    | '/api/auth/$'
    | '/app/$orgSlug/changelog'
    | '/app/$orgSlug/todo'
    | '/app/all/deals'
    | '/app/all/participations'
    | '/app/all/reports'
    | '/app/$orgSlug/'
    | '/app/all/'
    | '/app/$orgSlug/cash/$accountId'
    | '/app/$orgSlug/deals/$dealId'
    | '/app/$orgSlug/participations/$companyId'
    | '/app/$orgSlug/settings/general'
    | '/app/$orgSlug/settings/integrations'
    | '/app/$orgSlug/settings/invitations'
    | '/app/$orgSlug/settings/members'
    | '/app/$orgSlug/cash/'
    | '/app/$orgSlug/deals/'
    | '/app/$orgSlug/participations/'
    | '/app/$orgSlug/passif/'
    | '/app/$orgSlug/pointage/'
    | '/app/$orgSlug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/all': {
      id: '/app/all'
      path: '/all'
      fullPath: '/app/all'
      preLoaderRoute: typeof AppAllRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$orgSlug': {
      id: '/app/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/all/': {
      id: '/app/all/'
      path: '/'
      fullPath: '/app/all/'
      preLoaderRoute: typeof AppAllIndexRouteImport
      parentRoute: typeof AppAllRouteRoute
    }
    '/app/$orgSlug/': {
      id: '/app/$orgSlug/'
      path: '/'
      fullPath: '/app/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/all/reports': {
      id: '/app/all/reports'
      path: '/reports'
      fullPath: '/app/all/reports'
      preLoaderRoute: typeof AppAllReportsRouteImport
      parentRoute: typeof AppAllRouteRoute
    }
    '/app/all/participations': {
      id: '/app/all/participations'
      path: '/participations'
      fullPath: '/app/all/participations'
      preLoaderRoute: typeof AppAllParticipationsRouteImport
      parentRoute: typeof AppAllRouteRoute
    }
    '/app/all/deals': {
      id: '/app/all/deals'
      path: '/deals'
      fullPath: '/app/all/deals'
      preLoaderRoute: typeof AppAllDealsRouteImport
      parentRoute: typeof AppAllRouteRoute
    }
    '/app/$orgSlug/todo': {
      id: '/app/$orgSlug/todo'
      path: '/todo'
      fullPath: '/app/$orgSlug/todo'
      preLoaderRoute: typeof AppOrgSlugTodoRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/changelog': {
      id: '/app/$orgSlug/changelog'
      path: '/changelog'
      fullPath: '/app/$orgSlug/changelog'
      preLoaderRoute: typeof AppOrgSlugChangelogRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug/settings': {
      id: '/app/$orgSlug/settings'
      path: '/settings'
      fullPath: '/app/$orgSlug/settings'
      preLoaderRoute: typeof AppOrgSlugSettingsRouteRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/settings/': {
      id: '/app/$orgSlug/settings/'
      path: '/'
      fullPath: '/app/$orgSlug/settings/'
      preLoaderRoute: typeof AppOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/pointage/': {
      id: '/app/$orgSlug/pointage/'
      path: '/pointage'
      fullPath: '/app/$orgSlug/pointage/'
      preLoaderRoute: typeof AppOrgSlugPointageIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/passif/': {
      id: '/app/$orgSlug/passif/'
      path: '/passif'
      fullPath: '/app/$orgSlug/passif/'
      preLoaderRoute: typeof AppOrgSlugPassifIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/participations/': {
      id: '/app/$orgSlug/participations/'
      path: '/participations'
      fullPath: '/app/$orgSlug/participations/'
      preLoaderRoute: typeof AppOrgSlugParticipationsIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/deals/': {
      id: '/app/$orgSlug/deals/'
      path: '/deals'
      fullPath: '/app/$orgSlug/deals/'
      preLoaderRoute: typeof AppOrgSlugDealsIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/cash/': {
      id: '/app/$orgSlug/cash/'
      path: '/cash'
      fullPath: '/app/$orgSlug/cash/'
      preLoaderRoute: typeof AppOrgSlugCashIndexRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/settings/members': {
      id: '/app/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/app/$orgSlug/settings/members'
      preLoaderRoute: typeof AppOrgSlugSettingsMembersRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/settings/invitations': {
      id: '/app/$orgSlug/settings/invitations'
      path: '/invitations'
      fullPath: '/app/$orgSlug/settings/invitations'
      preLoaderRoute: typeof AppOrgSlugSettingsInvitationsRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/settings/integrations': {
      id: '/app/$orgSlug/settings/integrations'
      path: '/integrations'
      fullPath: '/app/$orgSlug/settings/integrations'
      preLoaderRoute: typeof AppOrgSlugSettingsIntegrationsRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/settings/general': {
      id: '/app/$orgSlug/settings/general'
      path: '/general'
      fullPath: '/app/$orgSlug/settings/general'
      preLoaderRoute: typeof AppOrgSlugSettingsGeneralRouteImport
      parentRoute: typeof AppOrgSlugSettingsRouteRoute
    }
    '/app/$orgSlug/participations/$companyId': {
      id: '/app/$orgSlug/participations/$companyId'
      path: '/participations/$companyId'
      fullPath: '/app/$orgSlug/participations/$companyId'
      preLoaderRoute: typeof AppOrgSlugParticipationsCompanyIdRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/deals/$dealId': {
      id: '/app/$orgSlug/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/app/$orgSlug/deals/$dealId'
      preLoaderRoute: typeof AppOrgSlugDealsDealIdRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/cash/$accountId': {
      id: '/app/$orgSlug/cash/$accountId'
      path: '/cash/$accountId'
      fullPath: '/app/$orgSlug/cash/$accountId'
      preLoaderRoute: typeof AppOrgSlugCashAccountIdRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
  }
}

interface AppOrgSlugSettingsRouteRouteChildren {
  AppOrgSlugSettingsGeneralRoute: typeof AppOrgSlugSettingsGeneralRoute
  AppOrgSlugSettingsIntegrationsRoute: typeof AppOrgSlugSettingsIntegrationsRoute
  AppOrgSlugSettingsInvitationsRoute: typeof AppOrgSlugSettingsInvitationsRoute
  AppOrgSlugSettingsMembersRoute: typeof AppOrgSlugSettingsMembersRoute
  AppOrgSlugSettingsIndexRoute: typeof AppOrgSlugSettingsIndexRoute
}

const AppOrgSlugSettingsRouteRouteChildren: AppOrgSlugSettingsRouteRouteChildren =
  {
    AppOrgSlugSettingsGeneralRoute: AppOrgSlugSettingsGeneralRoute,
    AppOrgSlugSettingsIntegrationsRoute: AppOrgSlugSettingsIntegrationsRoute,
    AppOrgSlugSettingsInvitationsRoute: AppOrgSlugSettingsInvitationsRoute,
    AppOrgSlugSettingsMembersRoute: AppOrgSlugSettingsMembersRoute,
    AppOrgSlugSettingsIndexRoute: AppOrgSlugSettingsIndexRoute,
  }

const AppOrgSlugSettingsRouteRouteWithChildren =
  AppOrgSlugSettingsRouteRoute._addFileChildren(
    AppOrgSlugSettingsRouteRouteChildren,
  )

interface AppOrgSlugRouteRouteChildren {
  AppOrgSlugSettingsRouteRoute: typeof AppOrgSlugSettingsRouteRouteWithChildren
  AppOrgSlugChangelogRoute: typeof AppOrgSlugChangelogRoute
  AppOrgSlugTodoRoute: typeof AppOrgSlugTodoRoute
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
  AppOrgSlugCashAccountIdRoute: typeof AppOrgSlugCashAccountIdRoute
  AppOrgSlugDealsDealIdRoute: typeof AppOrgSlugDealsDealIdRoute
  AppOrgSlugParticipationsCompanyIdRoute: typeof AppOrgSlugParticipationsCompanyIdRoute
  AppOrgSlugCashIndexRoute: typeof AppOrgSlugCashIndexRoute
  AppOrgSlugDealsIndexRoute: typeof AppOrgSlugDealsIndexRoute
  AppOrgSlugParticipationsIndexRoute: typeof AppOrgSlugParticipationsIndexRoute
  AppOrgSlugPassifIndexRoute: typeof AppOrgSlugPassifIndexRoute
  AppOrgSlugPointageIndexRoute: typeof AppOrgSlugPointageIndexRoute
}

const AppOrgSlugRouteRouteChildren: AppOrgSlugRouteRouteChildren = {
  AppOrgSlugSettingsRouteRoute: AppOrgSlugSettingsRouteRouteWithChildren,
  AppOrgSlugChangelogRoute: AppOrgSlugChangelogRoute,
  AppOrgSlugTodoRoute: AppOrgSlugTodoRoute,
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
  AppOrgSlugCashAccountIdRoute: AppOrgSlugCashAccountIdRoute,
  AppOrgSlugDealsDealIdRoute: AppOrgSlugDealsDealIdRoute,
  AppOrgSlugParticipationsCompanyIdRoute:
    AppOrgSlugParticipationsCompanyIdRoute,
  AppOrgSlugCashIndexRoute: AppOrgSlugCashIndexRoute,
  AppOrgSlugDealsIndexRoute: AppOrgSlugDealsIndexRoute,
  AppOrgSlugParticipationsIndexRoute: AppOrgSlugParticipationsIndexRoute,
  AppOrgSlugPassifIndexRoute: AppOrgSlugPassifIndexRoute,
  AppOrgSlugPointageIndexRoute: AppOrgSlugPointageIndexRoute,
}

const AppOrgSlugRouteRouteWithChildren = AppOrgSlugRouteRoute._addFileChildren(
  AppOrgSlugRouteRouteChildren,
)

interface AppAllRouteRouteChildren {
  AppAllDealsRoute: typeof AppAllDealsRoute
  AppAllParticipationsRoute: typeof AppAllParticipationsRoute
  AppAllReportsRoute: typeof AppAllReportsRoute
  AppAllIndexRoute: typeof AppAllIndexRoute
}

const AppAllRouteRouteChildren: AppAllRouteRouteChildren = {
  AppAllDealsRoute: AppAllDealsRoute,
  AppAllParticipationsRoute: AppAllParticipationsRoute,
  AppAllReportsRoute: AppAllReportsRoute,
  AppAllIndexRoute: AppAllIndexRoute,
}

const AppAllRouteRouteWithChildren = AppAllRouteRoute._addFileChildren(
  AppAllRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppOrgSlugRouteRoute: typeof AppOrgSlugRouteRouteWithChildren
  AppAllRouteRoute: typeof AppAllRouteRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  AppMeRoute: typeof AppMeRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrgSlugRouteRoute: AppOrgSlugRouteRouteWithChildren,
  AppAllRouteRoute: AppAllRouteRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  AppMeRoute: AppMeRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
